
DEF_CMD( PUSH   ,push   )
DEF_CMD( POP    ,pop    )
DEF_CMD( OUTT   ,out    )
DEF_CMD( ADD    ,add    )
DEF_CMD( SCAN   ,scan   )
DEF_CMD( DIFF   ,diff   )
DEF_CMD( MULT   ,mult   )
DEF_CMD( DIV    ,div    )
DEF_CMD( SQRT   ,sqrt   )
DEF_CMD( PUSHREG,pushreg)
DEF_CMD( POPREG ,popreg )
DEF_CMD( PUSHOP ,pushop )
DEF_CMD( POPOP  ,popop  )
DEF_CMD( JUMP   ,jump   )
DEF_CMD( JUMPE  ,jumpe  )
DEF_CMD( JUMPNE ,jumpne )
DEF_CMD( JUMPM  ,jumpm  )
DEF_CMD( JUMPME ,jumpme )
DEF_CMD( JUMPL  ,jumpl  )
DEF_CMD( JUMPLE ,jumple )
DEF_CMD( LABEL  ,label  )
DEF_CMD( END    ,End    )
DEF_CMD( MEOW   ,meow   )
DEF_CMD( CALL   ,call   )
DEF_CMD( RET    ,ret    )
DEF_CMD( E      ,e      )
DEF_CMD( NE     ,ne     )
DEF_CMD( M      ,m      )
DEF_CMD( ME     ,me     )
DEF_CMD( L      ,l      )
DEF_CMD( LE     ,le     )
//DEF_CMD( EOF    ,EOF    )


//DEF_CMD (type, number )


