
DEF_OPER (ADD,  "+", "add")
DEF_OPER (SUB,  "-", "diff")
DEF_OPER (MULT, "*", "mult")
DEF_OPER (DIV,  "/", "div")
DEF_OPER (LQUOT, "(", "lquot" )
DEF_OPER (RQUOT, ")", "rquot" )
DEF_OPER (LFIGURE, "{", "lfigure")
DEF_OPER (RFIGURE, "}", "rfigure")
DEF_OPER (ASSIGN, "=", "\n")
DEF_OPER (MEOW, "meow", "meow")
DEF_OPER (EQUAL,"==","e")
DEF_OPER (NEQUAL,"!=","ne")
DEF_OPER (MORE,">","m")
DEF_OPER (MOREE,">=","me")
DEF_OPER (LESS,"<","l")
DEF_OPER (LESSE,"<=","le")
DEF_OPER (SQRT, "sqrt", "sqrt")
DEF_OPER (PRINTF, "printf", "out")
DEF_OPER (COMMA, ",", "\n")
//DEF_OPER (IF, "if", "poka chto blablabla")

/*DEF_OPER (ADD, )
DEF_OPER (ADD, )
DEF_OPER (ADD, )*/
